
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  selector:
    matchLabels:
      app: nginx-deploy
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: app_runtime_stage=staging
    spec:
      containers:
      - name: nginx-deploy
        image: nginx:1.7.9
        ports:
        - containerPort: 80
